name: battleships-backend-ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./battleships-backend
    - name: Build with Gradle
      run: ./gradlew build -i
      working-directory: ./battleships-backend
    - name: Generate coverage report
      run: ./gradlew codeCoverageReport
      working-directory: ./battleships-backend
    - name: Upload coverage report
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${{CODECOV_TOKEN}}
      working-directory: ./battleships-backend
